### mpv Catppuccin theme
# Main mpv options
background-color='#000000'
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

# Stats script options
# Options are on separate lines for clarity
# Colors are in #BBGGRR format
script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=f7a6cb
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=f7a6cb

# External script options
# It is fine to leave these here even if one does not use these scripts because they are just ignored unless a script uses them

# UOSC options
script-opts-append=uosc-color=foreground=cba6f7,foreground_text=313244,background=1e1e2e,background_text=cdd6f4,curtain=181825,success=a6e3a1,error=f38ba8

### Video
vo=gpu
hwdec=vaapi

### OSD
# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no
osd-font="Inter Regular"
osd-font-size=24

### Window
# uosc will draw its own window controls and border if you disable window border
border=no
# Don't allow new windows to be larger than the screen
autofit-larger=100%x100%
# Disable indicators when nothing is playing
script-opts-append=uosc-disable_elements=idle_indicator

### Watch Later
#max_parallel_downloads=10
# Always save the current playback position on quit 
save-position-on-quit=yes

### Program Behavior
idle=yes
reset-on-next-file=pause, fullscreen, volume

# Video format/quality that is directly passed to youtube-dl. 480p in this instance
#ytdl-format=135+140
ytdl-format=bv[height<=?480][vcodec!*=av01]+ba

### GPU renderer options && Miscellaneous
# Reduce stuttering caused by mismatches in the video fps and display refresh rate (also known as judder). 
#[reduce-judder]
#video-sync=display-resample
#interpolation=yes

[autoloop]
profile-cond=duration <= 60
profile-restore=copy-equal
loop-file=inf

screenshot-template="%F - [%P] (%#01n)"
screenshot-directory=~/Pictures/Screenshots/

osc=no


